import { FoodItem } from '@/types/types';

const now = Date.now();

export const mockFoodItems: FoodItem[] = [
  // Proteins
  {
    id: 'food-chicken-breast',
    name: 'Chicken Breast',
    category: 'proteins',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminB6: 0.5,
    vitaminB12: 0.3,
    niacin: 14.8,
    phosphorus: 220,
    selenium: 27,
    zinc: 1,
  },
  {
    id: 'food-salmon',
    name: 'Salmon',
    category: 'proteins',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminD: 11,
    vitaminB12: 3.2,
    selenium: 41,
  },
  {
    id: 'food-eggs',
    name: 'Eggs',
    category: 'proteins',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminA: 540,
    vitaminD: 2,
    vitaminB12: 0.9,
    choline: 251,
    selenium: 30,
  },
  {
    id: 'food-ground-beef',
    name: 'Ground Beef (80/20)',
    category: 'proteins',
    calories: 254,
    protein: 17,
    carbs: 0,
    fat: 20,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    iron: 2.1,
    zinc: 4.8,
    vitaminB12: 2.4,
    niacin: 4.8,
  },

  // Dairy
  {
    id: 'food-greek-yogurt',
    name: 'Greek Yogurt (Plain)',
    category: 'dairy',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    calcium: 110,
    vitaminB12: 0.8,
    phosphorus: 135,
  },
  {
    id: 'food-milk',
    name: 'Whole Milk',
    category: 'dairy',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'ml',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    calcium: 113,
    vitaminD: 1.3,
    vitaminB12: 0.4,
  },
  {
    id: 'food-cheese-cheddar',
    name: 'Cheddar Cheese',
    category: 'dairy',
    calories: 403,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    calcium: 721,
    vitaminA: 1242,
    phosphorus: 512,
    zinc: 3.1,
  },

  // Grains
  {
    id: 'food-brown-rice',
    name: 'Brown Rice (Cooked)',
    category: 'grains',
    calories: 112,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    fiber: 1.8,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    manganese: 1.1,
    selenium: 10,
    magnesium: 43,
  },
  {
    id: 'food-oatmeal',
    name: 'Oatmeal (Cooked)',
    category: 'grains',
    calories: 71,
    protein: 2.5,
    carbs: 12,
    fat: 1.5,
    fiber: 1.7,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    manganese: 0.6,
    phosphorus: 77,
    magnesium: 27,
    iron: 1,
  },
  {
    id: 'food-whole-wheat-bread',
    name: 'Whole Wheat Bread',
    category: 'grains',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 6,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    thiamin: 0.4,
    niacin: 5,
    folate: 44,
    iron: 2.5,
  },
  {
    id: 'food-pasta',
    name: 'Pasta (Cooked)',
    category: 'grains',
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    thiamin: 0.1,
    folate: 18,
    selenium: 26,
  },

  // Vegetables
  {
    id: 'food-broccoli',
    name: 'Broccoli',
    category: 'vegetables',
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminC: 89,
    vitaminK: 102,
    folate: 63,
    calcium: 47,
  },
  {
    id: 'food-spinach',
    name: 'Spinach',
    category: 'vegetables',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminA: 9377,
    vitaminC: 28,
    vitaminK: 483,
    folate: 194,
    iron: 2.7,
    calcium: 99,
  },
  {
    id: 'food-carrots',
    name: 'Carrots',
    category: 'vegetables',
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminA: 16706,
    vitaminK: 13,
    potassium: 320,
  },
  {
    id: 'food-sweet-potato',
    name: 'Sweet Potato',
    category: 'vegetables',
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminA: 14187,
    vitaminC: 2.4,
    manganese: 0.3,
    potassium: 337,
  },

  // Fruits
  {
    id: 'food-banana',
    name: 'Banana',
    category: 'fruits',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminC: 8.7,
    vitaminB6: 0.4,
    potassium: 358,
    magnesium: 27,
  },
  {
    id: 'food-apple',
    name: 'Apple',
    category: 'fruits',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminC: 4.6,
    potassium: 107,
  },
  {
    id: 'food-blueberries',
    name: 'Blueberries',
    category: 'fruits',
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminC: 9.7,
    vitaminK: 19,
    manganese: 0.3,
  },
  {
    id: 'food-strawberries',
    name: 'Strawberries',
    category: 'fruits',
    calories: 32,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminC: 58.8,
    folate: 24,
    potassium: 153,
    manganese: 0.4,
  },

  // Fats & Oils
  {
    id: 'food-olive-oil',
    name: 'Olive Oil',
    category: 'fats',
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'ml',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminE: 14,
    vitaminK: 60,
  },
  {
    id: 'food-avocado',
    name: 'Avocado',
    category: 'fats',
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 15,
    fiber: 6.7,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminK: 21,
    folate: 81,
    vitaminC: 10,
    potassium: 485,
  },
  {
    id: 'food-almonds',
    name: 'Almonds',
    category: 'fats',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12.5,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminE: 25.6,
    calcium: 269,
    magnesium: 270,
    phosphorus: 481,
  },
  {
    id: 'food-peanut-butter',
    name: 'Peanut Butter',
    category: 'fats',
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 8,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminE: 8.3,
    niacin: 13.4,
    magnesium: 168,
  },

  // Beverages
  {
    id: 'food-water',
    name: 'Water',
    category: 'beverages',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'ml',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'food-coffee',
    name: 'Black Coffee',
    category: 'beverages',
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'ml',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'food-green-tea',
    name: 'Green Tea',
    category: 'beverages',
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 100,
    servingUnit: 'ml',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'food-orange-juice',
    name: 'Orange Juice',
    category: 'beverages',
    calories: 45,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    servingSize: 100,
    servingUnit: 'ml',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    vitaminC: 50,
    folate: 30,
    potassium: 200,
  },

  // Snacks
  {
    id: 'food-protein-bar',
    name: 'Protein Bar',
    brand: 'Generic',
    category: 'snacks',
    calories: 200,
    protein: 20,
    carbs: 22,
    fat: 7,
    fiber: 3,
    servingSize: 60,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    calcium: 150,
    iron: 2,
  },
  {
    id: 'food-dark-chocolate',
    name: 'Dark Chocolate (70-85%)',
    category: 'snacks',
    calories: 598,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    fiber: 11,
    servingSize: 100,
    servingUnit: 'g',
    isVerified: true,
    createdAt: now,
    updatedAt: now,
    iron: 11.9,
    magnesium: 228,
    copper: 1.8,
    manganese: 1.9,
  },
];
